import type { EventSourceWithCredentials } from './types';

const tenantId = 'tenant-demo';

export const mockEventSources: EventSourceWithCredentials[] = [
	{
		id: 'source-idp-demo',
		tenant_id: tenantId,
		source_name: 'Demo identity provider',
		source_type: 'idp',
		payload_format: 'json',
		vendor: 'Keycloak',
		external_reference: null,
		status: 'active',
		created_at: '2026-08-20T09:24:00Z',
		updated_at: '2026-08-20T09:24:00Z',
		credentials: [
			{
				id: 'credential-primary-demo',
				tenant_id: tenantId,
				event_source_id: 'source-idp-demo',
				credential_name: 'Primary ingestion key',
				credential_type: 'api_key',
				key_id: 'ing-••••••7A2F',
				key_hash: 'mock-key-hash-primary',
				status: 'active',
				expires_at: null,
				last_used_at: '2026-08-21T09:22:00Z',
				created_at: '2026-08-20T09:24:00Z',
				rotated_at: null,
			},
			{
				id: 'credential-backup-demo',
				tenant_id: tenantId,
				event_source_id: 'source-idp-demo',
				credential_name: 'Backup ingestion key',
				credential_type: 'api_key',
				key_id: 'ing-••••••B814',
				key_hash: 'mock-key-hash-backup',
				status: 'active',
				expires_at: '2026-12-31T23:59:59Z',
				last_used_at: null,
				created_at: '2026-08-20T09:24:00Z',
				rotated_at: null,
			},
		],
	},
	{
		id: 'source-siem-demo',
		tenant_id: tenantId,
		source_name: 'Security event relay',
		source_type: 'siem',
		payload_format: 'syslog',
		vendor: 'Internal relay',
		external_reference: null,
		status: 'active',
		created_at: '2026-08-20T09:24:00Z',
		updated_at: '2026-08-20T09:24:00Z',
		credentials: [
			{
				id: 'credential-relay-demo',
				tenant_id: tenantId,
				event_source_id: 'source-siem-demo',
				credential_name: 'Relay ingestion key',
				credential_type: 'api_key',
				key_id: 'ing-••••••91C4',
				key_hash: 'mock-key-hash-relay',
				status: 'active',
				expires_at: '2026-09-30T23:59:59Z',
				last_used_at: '2026-08-21T09:06:00Z',
				created_at: '2026-08-20T09:24:00Z',
				rotated_at: null,
			},
		],
	},
];
