import type { ThreatEvent } from './types';

const baseEvents: ThreatEvent[] = [
	{
		id: 'evt-001',
		time: '09:24:31',
		initials: 'JD',
		user: 'j••••@example.com',
		signInType: 'Okta SSO',
		result: 'Success',
		risk: 'Safe',
		tone: 'safe',
		score: 0.21,
		response: 'No action taken',
		device: 'MacOS · Chrome',
		network: '203.0.113.24',
		observedSignals: [],
		responseActivity: [],
	},
	{
		id: 'evt-002',
		time: '09:20:17',
		initials: 'LB',
		user: 'l••••@example.com',
		signInType: 'Azure AD',
		result: 'Success',
		risk: 'Caution',
		tone: 'caution',
		score: 0.365,
		response: 'Ask for extra verification',
		device: 'Windows · Edge',
		network: '198.51.100.77',
		observedSignals: [
			{
				label: 'Device variety',
				observed: 'New device',
				baseline: 'Higher than normal',
			},
			{
				label: 'Most-used device',
				observed: 'Windows · Edge',
				baseline: 'Windows · Edge',
			},
			{
				label: 'Login timing',
				observed: '01:20 (local time)',
				baseline: 'Typical',
			},
			{
				label: 'Recent sign-in frequency',
				observed: '3 in 24 hours',
				baseline: 'Higher than normal',
			},
			{
				label: 'Time since last sign-in',
				observed: '25 days',
				baseline: 'Higher than normal',
			},
		],
		responseActivity: [
			{ time: '09:20:17', label: 'Extra verification challenge sent' },
			{ time: '09:20:22', label: 'User completed verification' },
			{ time: '09:20:29', label: 'Success' },
		],
	},
	{
		id: 'evt-003',
		time: '09:18:42',
		initials: 'RP',
		user: 'r••••@example.com',
		signInType: 'Okta SSO',
		result: 'Failed',
		risk: 'Lockout',
		tone: 'lockout',
		score: 0.463,
		response: 'End session',
		device: 'iOS · Mobile Safari',
		network: '185.199.108.15',
		observedSignals: [],
		responseActivity: [],
	},
	{
		id: 'evt-004',
		time: '09:15:09',
		initials: 'AT',
		user: 'a••••@example.com',
		signInType: 'Okta SSO',
		result: 'Failed',
		risk: 'Lockout',
		tone: 'lockout',
		score: 0.582,
		response: 'Lock account',
		device: 'Windows · Chrome',
		network: '203.0.113.55',
		observedSignals: [],
		responseActivity: [],
	},
	{
		id: 'evt-005',
		time: '09:14:03',
		initials: 'KM',
		user: 'k••••@example.com',
		signInType: 'Azure AD',
		result: 'Success',
		risk: 'Safe',
		tone: 'safe',
		score: 0.193,
		response: 'No action taken',
		device: 'MacOS · Safari',
		network: '203.0.113.90',
		observedSignals: [],
		responseActivity: [],
	},
	{
		id: 'evt-006',
		time: '09:12:55',
		initials: 'SM',
		user: 's••••@example.com',
		signInType: 'Okta SSO',
		result: 'Success',
		risk: 'Caution',
		tone: 'caution',
		score: 0.328,
		response: 'Monitor session',
		device: 'Android · Chrome',
		network: '198.51.100.23',
		observedSignals: [],
		responseActivity: [],
	},
];

export const mockThreatEvents: ThreatEvent[] = [
	...baseEvents,
	...Array.from({ length: 8 }, (_, index) => ({
		...baseEvents[index % baseEvents.length],
		id: `evt-${String(index + 7).padStart(3, '0')}`,
		time: `09:${String(10 - index).padStart(2, '0')}:00`,
	})),
];
