"""tenant soft delete and cascades

Revision ID: 1e93dba3a20f
Revises: ec04b7524602
Create Date: 2026-08-01 21:22:51.393810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e93dba3a20f'
down_revision: Union[str, Sequence[str], None] = 'ec04b7524602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_event_sources_tenant_id_tenants'), 'event_sources', type_='foreignkey')
    op.create_foreign_key(op.f('fk_event_sources_tenant_id_tenants'), 'event_sources', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_ingestion_credentials_event_source_id_event_sources'), 'ingestion_credentials', type_='foreignkey')
    op.drop_constraint(op.f('fk_ingestion_credentials_tenant_id_tenants'), 'ingestion_credentials', type_='foreignkey')
    op.create_foreign_key(op.f('fk_ingestion_credentials_event_source_id_event_sources'), 'ingestion_credentials', 'event_sources', ['event_source_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_ingestion_credentials_tenant_id_tenants'), 'ingestion_credentials', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_tenant_hash_key_versions_tenant_id_tenants'), 'tenant_hash_key_versions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tenant_hash_key_versions_tenant_id_tenants'), 'tenant_hash_key_versions', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_tenant_operating_modes_tenant_id_tenants'), 'tenant_operating_modes', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tenant_operating_modes_tenant_id_tenants'), 'tenant_operating_modes', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_tenant_threshold_profiles_tenant_id_tenants'), 'tenant_threshold_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tenant_threshold_profiles_tenant_id_tenants'), 'tenant_threshold_profiles', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('tenants', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'deleted_at')
    op.drop_constraint(op.f('fk_tenant_threshold_profiles_tenant_id_tenants'), 'tenant_threshold_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tenant_threshold_profiles_tenant_id_tenants'), 'tenant_threshold_profiles', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(op.f('fk_tenant_operating_modes_tenant_id_tenants'), 'tenant_operating_modes', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tenant_operating_modes_tenant_id_tenants'), 'tenant_operating_modes', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(op.f('fk_tenant_hash_key_versions_tenant_id_tenants'), 'tenant_hash_key_versions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tenant_hash_key_versions_tenant_id_tenants'), 'tenant_hash_key_versions', 'tenants', ['tenant_id'], ['id'])
    op.drop_constraint(op.f('fk_ingestion_credentials_tenant_id_tenants'), 'ingestion_credentials', type_='foreignkey')
    op.drop_constraint(op.f('fk_ingestion_credentials_event_source_id_event_sources'), 'ingestion_credentials', type_='foreignkey')
    op.create_foreign_key(op.f('fk_ingestion_credentials_tenant_id_tenants'), 'ingestion_credentials', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(op.f('fk_ingestion_credentials_event_source_id_event_sources'), 'ingestion_credentials', 'event_sources', ['event_source_id'], ['id'])
    op.drop_constraint(op.f('fk_event_sources_tenant_id_tenants'), 'event_sources', type_='foreignkey')
    op.create_foreign_key(op.f('fk_event_sources_tenant_id_tenants'), 'event_sources', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###
