"""provider registry and lifecycle fields

Revision ID: 1f0c4204efd9
Revises: 1e93dba3a20f
Create Date: 2026-08-06 20:47:14.081015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f0c4204efd9'
down_revision: Union[str, Sequence[str], None] = '1e93dba3a20f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    event_payload_format = sa.Enum(
        'json',
        'syslog',
        name='event_payload_format',
        create_type=False,
    )

    event_payload_format.create(op.get_bind(), checkfirst=True)

    op.create_table('provider_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_key', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('provider_type', sa.Enum('idp', 'siem', name='provider_type'), nullable=False),
    sa.Column('connection_method', sa.Enum('api_token', 'oauth_client_credentials', 'service_account', name='provider_connection_method'), nullable=False),
    sa.Column('supported_policy_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deprecated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_registry')),
    sa.UniqueConstraint('provider_key', name=op.f('uq_provider_registry_provider_key'))
    )
    op.create_table('tenant_provider_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('provider_registry_id', sa.UUID(), nullable=False),
    sa.Column('connection_name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('auth_realm', sa.String(length=255), nullable=True),
    sa.Column('client_id', sa.String(length=255), nullable=True),
    sa.Column('client_secret_ref', sa.String(length=255), nullable=True),
    sa.Column('api_token_ref', sa.String(length=255), nullable=True),
    sa.Column('external_tenant_reference', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'disabled', 'test_failed', name='tenant_provider_connection_status'), nullable=False),
    sa.Column('disabled_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_tested_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_test_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_registry_id'], ['provider_registry.id'], name=op.f('fk_tenant_provider_connections_provider_registry_id_provider_registry')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_provider_connections_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_provider_connections')),
    sa.UniqueConstraint('tenant_id', 'connection_name', name=op.f('uq_tenant_provider_connections_tenant_id'))
    )
    op.create_index(op.f('ix_tenant_provider_connections_provider_registry_id'), 'tenant_provider_connections', ['provider_registry_id'], unique=False)
    op.create_index(op.f('ix_tenant_provider_connections_status'), 'tenant_provider_connections', ['status'], unique=False)
    op.create_index(op.f('ix_tenant_provider_connections_tenant_id'), 'tenant_provider_connections', ['tenant_id'], unique=False)
    op.add_column('event_sources', sa.Column('payload_format', event_payload_format, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    event_payload_format = sa.Enum(
        'json',
        'syslog',
        name='event_payload_format',
        create_type=False,
    )

    op.drop_column('event_sources', 'payload_format')
    op.drop_index(op.f('ix_tenant_provider_connections_tenant_id'), table_name='tenant_provider_connections')
    op.drop_index(op.f('ix_tenant_provider_connections_status'), table_name='tenant_provider_connections')
    op.drop_index(op.f('ix_tenant_provider_connections_provider_registry_id'), table_name='tenant_provider_connections')
    op.drop_table('tenant_provider_connections')
    op.drop_table('provider_registry')

    event_payload_format.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
