"""initial schema

Revision ID: ec04b7524602
Revises:
Create Date: 2026-07-30 22:09:00.529618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec04b7524602'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'archived', name='tenant_status'), nullable=False),
    sa.Column('default_timezone', sa.String(length=100), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('slug', name=op.f('uq_tenants_slug'))
    )
    op.create_table('event_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('idp', 'siem', 'agent', 'manual_replay', name='event_source_type'), nullable=False),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'disabled', name='event_source_status'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_event_sources_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_sources'))
    )
    op.create_index(op.f('ix_event_sources_tenant_id'), 'event_sources', ['tenant_id'], unique=False)
    op.create_table('tenant_hash_key_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('algorithm', sa.String(length=100), nullable=False),
    sa.Column('salt_value', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('effective_to', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_hash_key_versions_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_hash_key_versions')),
    sa.UniqueConstraint('tenant_id', 'key_version', name=op.f('uq_tenant_hash_key_versions_tenant_id'))
    )
    op.create_index(op.f('ix_tenant_hash_key_versions_tenant_id'), 'tenant_hash_key_versions', ['tenant_id'], unique=False)
    op.create_table('tenant_operating_modes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Enum('shadow', 'alert_only', 'enforce', name='operating_mode'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('effective_to', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('changed_by', sa.String(length=255), nullable=True),
    sa.Column('change_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_operating_modes_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_operating_modes'))
    )
    op.create_index(op.f('ix_tenant_operating_modes_tenant_id'), 'tenant_operating_modes', ['tenant_id'], unique=False)
    op.create_table('tenant_threshold_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('caution_threshold', sa.Float(), nullable=False),
    sa.Column('lockout_threshold', sa.Float(), nullable=False),
    sa.Column('fusion_alpha', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('effective_to', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_threshold_profiles_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_threshold_profiles'))
    )
    op.create_index(op.f('ix_tenant_threshold_profiles_tenant_id'), 'tenant_threshold_profiles', ['tenant_id'], unique=False)
    op.create_table('ingestion_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('event_source_id', sa.UUID(), nullable=True),
    sa.Column('credential_name', sa.String(length=255), nullable=False),
    sa.Column('credential_type', sa.Enum('api_key', name='ingestion_credential_type'), nullable=False),
    sa.Column('key_id', sa.String(length=255), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('active', 'revoked', 'expired', name='ingestion_credential_status'), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rotated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_source_id'], ['event_sources.id'], name=op.f('fk_ingestion_credentials_event_source_id_event_sources')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_ingestion_credentials_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_credentials')),
    sa.UniqueConstraint('key_id', name=op.f('uq_ingestion_credentials_key_id'))
    )
    op.create_index(op.f('ix_ingestion_credentials_tenant_id'), 'ingestion_credentials', ['tenant_id'], unique=False)
    op.create_table('auth_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('event_source_id', sa.UUID(), nullable=False),
    sa.Column('ingestion_credential_id', sa.UUID(), nullable=True),
    sa.Column('source_event_id', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('outcome', sa.Enum('success', 'failure', 'challenge', 'logout', 'unknown', name='auth_event_outcome'), nullable=False),
    sa.Column('user_hash', sa.String(length=255), nullable=False),
    sa.Column('account_hash', sa.String(length=255), nullable=True),
    sa.Column('session_hash', sa.String(length=255), nullable=True),
    sa.Column('source_ip_hash', sa.String(length=255), nullable=True),
    sa.Column('source_ip_prefix', sa.String(length=50), nullable=True),
    sa.Column('device_hash', sa.String(length=255), nullable=True),
    sa.Column('host_hash', sa.String(length=255), nullable=True),
    sa.Column('auth_method', sa.String(length=100), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('location_country', sa.String(length=100), nullable=True),
    sa.Column('location_region', sa.String(length=100), nullable=True),
    sa.Column('occurred_hour', sa.Integer(), nullable=False),
    sa.Column('occurred_day_of_week', sa.Integer(), nullable=False),
    sa.Column('hash_key_version', sa.Integer(), nullable=False),
    sa.Column('payload_schema_version', sa.Integer(), nullable=False),
    sa.Column('raw_payload_redacted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('normalization_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_source_id'], ['event_sources.id'], name=op.f('fk_auth_events_event_source_id_event_sources')),
    sa.ForeignKeyConstraint(['ingestion_credential_id'], ['ingestion_credentials.id'], name=op.f('fk_auth_events_ingestion_credential_id_ingestion_credentials')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_auth_events_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_events')),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name=op.f('uq_auth_events_tenant_id'))
    )
    op.create_index(op.f('ix_auth_events_event_source_id'), 'auth_events', ['event_source_id'], unique=False)
    op.create_index(op.f('ix_auth_events_host_hash'), 'auth_events', ['host_hash'], unique=False)
    op.create_index(op.f('ix_auth_events_occurred_at'), 'auth_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_auth_events_tenant_id'), 'auth_events', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_auth_events_user_hash'), 'auth_events', ['user_hash'], unique=False)
    op.create_table('event_processing_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('auth_event_id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.Enum('score_event', 'send_alert', 'enforce_action', name='processing_job_type'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'dead_lettered', name='processing_run_status'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.String(length=255), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('queued_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['auth_event_id'], ['auth_events.id'], name=op.f('fk_event_processing_runs_auth_event_id_auth_events')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_event_processing_runs_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_processing_runs'))
    )
    op.create_index(op.f('ix_event_processing_runs_auth_event_id'), 'event_processing_runs', ['auth_event_id'], unique=False)
    op.create_index(op.f('ix_event_processing_runs_status'), 'event_processing_runs', ['status'], unique=False)
    op.create_index(op.f('ix_event_processing_runs_tenant_id'), 'event_processing_runs', ['tenant_id'], unique=False)
    op.create_table('feature_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('auth_event_id', sa.UUID(), nullable=False),
    sa.Column('processing_run_id', sa.UUID(), nullable=False),
    sa.Column('window_start', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('window_end', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('login_frequency', sa.Float(), nullable=True),
    sa.Column('avg_inter_event_time', sa.Float(), nullable=True),
    sa.Column('time_since_last_login', sa.Float(), nullable=True),
    sa.Column('unique_hosts', sa.Float(), nullable=True),
    sa.Column('host_entropy', sa.Float(), nullable=True),
    sa.Column('top_host_ratio', sa.Float(), nullable=True),
    sa.Column('degree_centrality', sa.Float(), nullable=True),
    sa.Column('hour_of_day', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('feature_version', sa.Integer(), nullable=False),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['auth_event_id'], ['auth_events.id'], name=op.f('fk_feature_snapshots_auth_event_id_auth_events')),
    sa.ForeignKeyConstraint(['processing_run_id'], ['event_processing_runs.id'], name=op.f('fk_feature_snapshots_processing_run_id_event_processing_runs')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_feature_snapshots_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_snapshots'))
    )
    op.create_index(op.f('ix_feature_snapshots_auth_event_id'), 'feature_snapshots', ['auth_event_id'], unique=False)
    op.create_index(op.f('ix_feature_snapshots_tenant_id'), 'feature_snapshots', ['tenant_id'], unique=False)
    op.create_table('host_interaction_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('auth_event_id', sa.UUID(), nullable=False),
    sa.Column('processing_run_id', sa.UUID(), nullable=False),
    sa.Column('window_start', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('window_end', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('user_hash', sa.String(length=255), nullable=False),
    sa.Column('host_hash', sa.String(length=255), nullable=False),
    sa.Column('interaction_count', sa.Integer(), nullable=False),
    sa.Column('last_interaction_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('snapshot_version', sa.Integer(), nullable=False),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['auth_event_id'], ['auth_events.id'], name=op.f('fk_host_interaction_snapshots_auth_event_id_auth_events')),
    sa.ForeignKeyConstraint(['processing_run_id'], ['event_processing_runs.id'], name=op.f('fk_host_interaction_snapshots_processing_run_id_event_processing_runs')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_host_interaction_snapshots_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_host_interaction_snapshots')),
    sa.UniqueConstraint('tenant_id', 'auth_event_id', 'processing_run_id', 'user_hash', 'host_hash', name=op.f('uq_host_interaction_snapshots_tenant_id'))
    )
    op.create_index(op.f('ix_host_interaction_snapshots_host_hash'), 'host_interaction_snapshots', ['host_hash'], unique=False)
    op.create_index(op.f('ix_host_interaction_snapshots_tenant_id'), 'host_interaction_snapshots', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_host_interaction_snapshots_user_hash'), 'host_interaction_snapshots', ['user_hash'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('auth_event_id', sa.UUID(), nullable=False),
    sa.Column('feature_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('processing_run_id', sa.UUID(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('threshold_profile_id', sa.UUID(), nullable=False),
    sa.Column('global_anomaly_score', sa.Float(), nullable=False),
    sa.Column('local_anomaly_score_raw', sa.Float(), nullable=False),
    sa.Column('local_anomaly_score_normalized', sa.Float(), nullable=False),
    sa.Column('fusion_alpha', sa.Float(), nullable=False),
    sa.Column('fused_anomaly_score', sa.Float(), nullable=False),
    sa.Column('caution_threshold_applied', sa.Float(), nullable=False),
    sa.Column('lockout_threshold_applied', sa.Float(), nullable=False),
    sa.Column('score_band', sa.Enum('safe', 'caution', 'lockout', name='score_band'), nullable=False),
    sa.Column('scored_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['auth_event_id'], ['auth_events.id'], name=op.f('fk_risk_scores_auth_event_id_auth_events')),
    sa.ForeignKeyConstraint(['feature_snapshot_id'], ['feature_snapshots.id'], name=op.f('fk_risk_scores_feature_snapshot_id_feature_snapshots')),
    sa.ForeignKeyConstraint(['processing_run_id'], ['event_processing_runs.id'], name=op.f('fk_risk_scores_processing_run_id_event_processing_runs')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_risk_scores_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['threshold_profile_id'], ['tenant_threshold_profiles.id'], name=op.f('fk_risk_scores_threshold_profile_id_tenant_threshold_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_scores'))
    )
    op.create_index(op.f('ix_risk_scores_auth_event_id'), 'risk_scores', ['auth_event_id'], unique=False)
    op.create_index(op.f('ix_risk_scores_score_band'), 'risk_scores', ['score_band'], unique=False)
    op.create_index(op.f('ix_risk_scores_scored_at'), 'risk_scores', ['scored_at'], unique=False)
    op.create_index(op.f('ix_risk_scores_tenant_id'), 'risk_scores', ['tenant_id'], unique=False)
    op.create_table('policy_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('auth_event_id', sa.UUID(), nullable=False),
    sa.Column('risk_score_id', sa.UUID(), nullable=False),
    sa.Column('operating_mode_id', sa.UUID(), nullable=False),
    sa.Column('decision_band', sa.Enum('safe', 'caution', 'lockout', name='policy_decision_band'), nullable=False),
    sa.Column('recommended_action', sa.Enum('allow', 'step_up_mfa', 'terminate_session', 'lock_account', 'alert_only', 'none', name='policy_action'), nullable=False),
    sa.Column('final_action', sa.Enum('allow', 'step_up_mfa', 'terminate_session', 'lock_account', 'alert_only', 'none', name='policy_final_action'), nullable=False),
    sa.Column('decision_reason', sa.String(length=500), nullable=True),
    sa.Column('decision_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('decided_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['auth_event_id'], ['auth_events.id'], name=op.f('fk_policy_decisions_auth_event_id_auth_events')),
    sa.ForeignKeyConstraint(['operating_mode_id'], ['tenant_operating_modes.id'], name=op.f('fk_policy_decisions_operating_mode_id_tenant_operating_modes')),
    sa.ForeignKeyConstraint(['risk_score_id'], ['risk_scores.id'], name=op.f('fk_policy_decisions_risk_score_id_risk_scores')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_policy_decisions_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_decisions'))
    )
    op.create_index(op.f('ix_policy_decisions_auth_event_id'), 'policy_decisions', ['auth_event_id'], unique=False)
    op.create_index(op.f('ix_policy_decisions_decided_at'), 'policy_decisions', ['decided_at'], unique=False)
    op.create_index(op.f('ix_policy_decisions_tenant_id'), 'policy_decisions', ['tenant_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('policy_decision_id', sa.UUID(), nullable=False),
    sa.Column('risk_score_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', name='alert_severity'), nullable=False),
    sa.Column('status', sa.Enum('open', 'acknowledged', 'resolved', name='alert_status'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('alert_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['policy_decision_id'], ['policy_decisions.id'], name=op.f('fk_alerts_policy_decision_id_policy_decisions')),
    sa.ForeignKeyConstraint(['risk_score_id'], ['risk_scores.id'], name=op.f('fk_alerts_risk_score_id_risk_scores')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_alerts_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_tenant_id'), 'alerts', ['tenant_id'], unique=False)
    op.create_table('enforcement_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('policy_decision_id', sa.UUID(), nullable=False),
    sa.Column('event_source_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.Enum('step_up_mfa', 'terminate_session', 'lock_account', name='enforcement_action_type'), nullable=False),
    sa.Column('target_user_hash', sa.String(length=255), nullable=False),
    sa.Column('integration_name', sa.String(length=255), nullable=False),
    sa.Column('request_payload_redacted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('pending', 'sent', 'succeeded', 'failed', 'skipped', name='enforcement_action_status'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('external_action_id', sa.String(length=255), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('requested_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_source_id'], ['event_sources.id'], name=op.f('fk_enforcement_actions_event_source_id_event_sources')),
    sa.ForeignKeyConstraint(['policy_decision_id'], ['policy_decisions.id'], name=op.f('fk_enforcement_actions_policy_decision_id_policy_decisions')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_enforcement_actions_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enforcement_actions'))
    )
    op.create_index(op.f('ix_enforcement_actions_requested_at'), 'enforcement_actions', ['requested_at'], unique=False)
    op.create_index(op.f('ix_enforcement_actions_status'), 'enforcement_actions', ['status'], unique=False)
    op.create_index(op.f('ix_enforcement_actions_tenant_id'), 'enforcement_actions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enforcement_actions_tenant_id'), table_name='enforcement_actions')
    op.drop_index(op.f('ix_enforcement_actions_status'), table_name='enforcement_actions')
    op.drop_index(op.f('ix_enforcement_actions_requested_at'), table_name='enforcement_actions')
    op.drop_table('enforcement_actions')
    op.drop_index(op.f('ix_alerts_tenant_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_policy_decisions_tenant_id'), table_name='policy_decisions')
    op.drop_index(op.f('ix_policy_decisions_decided_at'), table_name='policy_decisions')
    op.drop_index(op.f('ix_policy_decisions_auth_event_id'), table_name='policy_decisions')
    op.drop_table('policy_decisions')
    op.drop_index(op.f('ix_risk_scores_tenant_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_scored_at'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_score_band'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_auth_event_id'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_host_interaction_snapshots_user_hash'), table_name='host_interaction_snapshots')
    op.drop_index(op.f('ix_host_interaction_snapshots_tenant_id'), table_name='host_interaction_snapshots')
    op.drop_index(op.f('ix_host_interaction_snapshots_host_hash'), table_name='host_interaction_snapshots')
    op.drop_table('host_interaction_snapshots')
    op.drop_index(op.f('ix_feature_snapshots_tenant_id'), table_name='feature_snapshots')
    op.drop_index(op.f('ix_feature_snapshots_auth_event_id'), table_name='feature_snapshots')
    op.drop_table('feature_snapshots')
    op.drop_index(op.f('ix_event_processing_runs_tenant_id'), table_name='event_processing_runs')
    op.drop_index(op.f('ix_event_processing_runs_status'), table_name='event_processing_runs')
    op.drop_index(op.f('ix_event_processing_runs_auth_event_id'), table_name='event_processing_runs')
    op.drop_table('event_processing_runs')
    op.drop_index(op.f('ix_auth_events_user_hash'), table_name='auth_events')
    op.drop_index(op.f('ix_auth_events_tenant_id'), table_name='auth_events')
    op.drop_index(op.f('ix_auth_events_occurred_at'), table_name='auth_events')
    op.drop_index(op.f('ix_auth_events_host_hash'), table_name='auth_events')
    op.drop_index(op.f('ix_auth_events_event_source_id'), table_name='auth_events')
    op.drop_table('auth_events')
    op.drop_index(op.f('ix_ingestion_credentials_tenant_id'), table_name='ingestion_credentials')
    op.drop_table('ingestion_credentials')
    op.drop_index(op.f('ix_tenant_threshold_profiles_tenant_id'), table_name='tenant_threshold_profiles')
    op.drop_table('tenant_threshold_profiles')
    op.drop_index(op.f('ix_tenant_operating_modes_tenant_id'), table_name='tenant_operating_modes')
    op.drop_table('tenant_operating_modes')
    op.drop_index(op.f('ix_tenant_hash_key_versions_tenant_id'), table_name='tenant_hash_key_versions')
    op.drop_table('tenant_hash_key_versions')
    op.drop_index(op.f('ix_event_sources_tenant_id'), table_name='event_sources')
    op.drop_table('event_sources')
    op.drop_table('tenants')
    # ### end Alembic commands ###
